name: build-dotnet

on:
  workflow_call:
    inputs:
      buildConfiguration:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string

#permissions:
#  actions: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build 
      run: dotnet build --configuration ${{ inputs.buildConfiguration }} --no-restore

    - name: dotnet publish
      run: dotnet publish -c Release -o ./output

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: webapp
        path: output
