name: deploy-webapp

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      app-name:
        required: true
        type: string
    secrets:
      publish-profile:
        required: true
        
jobs:
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment }}
      steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: webapp
          path: output

      - name: 'Run Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ inputs.app-name }}
          publish-profile: ${{ secrets.publish-profile }}
          package: './output'
